### ISSUE TITLE
@processor.buffers are empty

### ISSUE THREAD

**Issue by lijianxun** [nttlabs/bosh-scaler#6]
Hello, I get a recurrent problem:  I can not get the calc in condition.match, then I find the @processor.buffers are empty in calc.
./config/sample.yml  
---
nats: &nats
  uri: mbus://10.158.246.80:4222
  user: nats
  pass: nats

rest: &rest
  endpoint_uri: https://10.158.246.80:25555
  user: admin
  password: admin
  disable_verify_certification: true

collectors:
  - class: BoshNatsCollector
    bosh_nats: *nats
    bosh_rest: *rest
  - class: CfVarzTsdbCollector # Optional for CF
    port: 4567

listeners:
  - class: BoshScaler
    bosh_rest: *rest
    interval: 60 # seconds
    buffer_size: 1000
    ui:
      enable: true
      port: 8888

logging:
    file: log/scaler.log
    level: debug
#My deployment manifest：
---
name: cf-deployment

releases:

networks:
- name: bosh
  type: manual
  subnets:
  - range: 10.158.246.0/25
    gateway: 10.158.246.1
    dns:
    - 114.114.114.114
    - 8.8.8.8
    static: ["10.158.246.80 - 10.158.246.109"]
    cloud_properties:
      net_id: f4396a36-ea3e-4a8d-8290-0b4ef80f540f
- name: elastic
  type: vip
  cloud_properties: {}

cloud:
  plugin: openstack
  properties:
    openstack:
      auth_url: http://10.158.12.200:5000/v2.0/tokens 
      tenant: admin # Replace with OpenStack tenant name
      username: admin # Replace with OpenStack username
      api_key: "123456" # Replace with your OpenStack password
      config_drive: cdrom
      aopenstack_region: regionOne # Optional
      default_key_name: lijx # OpenStack Keypair name
      private_key: lijx.pem # Path to OpenStack Keypair private key
      default_security_groups: [default]

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

compilation:
  workers: 3
  network: bosh
  reuse_compilation_vms: true
  type: vip
  cloud_properties: {}

cloud:
  plugin: openstack
  properties:
    openstack:
      tenant: admin # Replace with OpenStack tenant name
      username: admin # Replace with OpenStack username
      api_key: "123456" # Replace with your OpenStack password
      config_drive: cdrom
      aopenstack_region: regionOne # Optional
      default_key_name: lijx # OpenStack Keypair name
      private_key: lijx.pem # Path to OpenStack Keypair private key
      default_security_groups: [default]

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

compilation:
  workers: 3
  network: bosh
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.large

resource_pools:
  - name: small
    network: bosh
    size: 20
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: 3100
    cloud_properties:
      instance_type: m1.small

  - name: medium
    network: bosh
    size: 6
    stemcell:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent
      version: 3100
    cloud_properties:
      instance_type: m1.medium

jobs:
- name: nats_z1
  instances: 2
  resource_pool: small
  templates:
  - {name: nats, release: cf}
  - {name: nats_stream_forwarder, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.81,10.158.246.94]

- name: etcd_z1
  instances: 1
  resource_pool: small
  persistent_disk: 40960
  templates:
  - {name: etcd, release: cf}
  - {name: etcd_metrics_server, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.82]
  properties:
    etcd_metrics_server:
      nats:
        machines: [10.158.246.81,10.158.246.94]
        password: PASSWORD
        username: nats

- name: nfs_z1
  instances: 1
  persistent_disk: 40960
  resource_pool: small
  templates:
  - {name: debian_nfs_server, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.83]

- name: postgres_z1
  instances: 1
  persistent_disk: 40960
  resource_pool: small
  templates:
  - {name: postgres, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.84]
  update:
    serial: true

- name: api_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: cloud_controller_ng, release: cf}
  - {name: cloud_controller_worker, release: cf}
  - {name: cloud_controller_clock, release: cf}
  - {name: metron_agent, release: cf}
  - {name: nfs_mounter, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.85]
  properties:
    nfs_server:
      address: 10.158.246.83
      allow_from_entries: [10.158.246.0/25]

- name: ha_proxy_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: haproxy, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.86]
  properties:
    ha_proxy:
      ssl_pem: |
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
        -----BEGIN RSA PRIVATE KEY-----
        -----END RSA PRIVATE KEY-----

    router:
      servers:
        z1: [10.158.246.91]

- name: hm9000_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: hm9000, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.87]

- name: doppler_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: doppler, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.88]
  properties:
    doppler: {zone: nova}
    doppler_endpoint:
      shared_secret: PASSWORD

- name: loggregator_trafficcontroller_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: loggregator_trafficcontroller, release: cf}
  - {name: metron_agent, release: cf}
    static_ips: [10.158.246.89]
  properties:
    traffic_controller: {zone: nova}

- name: uaa_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: uaa, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.90]
  properties:
    login:
      catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    uaa:
      admin:
        client_secret: PASSWORD
      batch:
        password: PASSWORD
        username: batch_user
      cc:
        client_secret: PASSWORD
      scim:
        userids_enabled: true
        users:
    uaadb:
      address: 10.158.246.84
      databases:
      - {name: uaadb, tag: uaa}
      db_scheme: postgresql
      port: 5524
      roles:
      - {name: uaaadmin, password: PASSWORD, tag: admin}

- name: router_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: gorouter, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.91]
  properties:
    dropsonde: {enabled: true}

- name: runner_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: dea_next, release: cf}
  - {name: dea_logging_agent, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.92]
  properties:
    dea_next: {zone: nova}

- name: stats_z1
  instances: 1
  resource_pool: small
  templates:
  - {name: collector, release: cf}
  - {name: metron_agent, release: cf}
  networks:
  - name: bosh
    static_ips: [10.158.246.93]
  properties:
    collector:
      use_tsdb: true
      deployment_name: cf-deployment
    opentsdb:
      address: 192.168.37.154
      port: 4567

scale:
  jobs:
  - name: runner_z1
    cooldown: 300
    out:
      limit: 3
      conditions:
        - class: CfVarzAverage              # Cloud Foundry Metrics
          varz_job: DEA                     # varz job name
          varz_key: available_memory_ratio  # varz key name
          smaller_than: 20
          duration: 300
        - class: CpuAverage                 # CPU usage average
          larger_than: 5                   # Threshold (percent)
          duration: 30                     # For calculating average
        - class: MemoryAverage              # Memory usage average
          larger_than: 90                   # Threshold (percent)
          duration: 30
    in:
      limit: 1
      conditions:
        - class: CfVarzAverage
          varz_job: DEA
          varz_key: available_memory_ratio
          larger_than: 50
          duration: 300

properties:
  networks: {apps: bosh}
  app_domains: [10.158.246.86.xip.io]
  cc:
    allow_app_ssh_access: false
    bulk_api_password: PASSWORD
    db_encryption_key: PASSWORD
    default_running_security_groups: [public_networks, dns]
    default_staging_security_groups: [public_networks, dns]
    install_buildpacks:
    - {name: java_buildpack, package: buildpack_java}
    - {name: ruby_buildpack, package: buildpack_ruby}
    - {name: nodejs_buildpack, package: buildpack_nodejs}
    - {name: go_buildpack, package: buildpack_go}
    - {name: python_buildpack, package: buildpack_python}
    - {name: php_buildpack, package: buildpack_php}
    - {name: staticfile_buildpack, package: buildpack_staticfile}
    - {name: binary_buildpack, package: buildpack_binary}
    internal_api_password: PASSWORD
    quota_definitions:
      default:
        memory_limit: 102400
        non_basic_services_allowed: true
        total_routes: 1000
        total_services: -1
    security_group_definitions:
    - name: public_networks
      rules:
      - {destination: 0.0.0.0-9.255.255.255, protocol: all}
      - {destination: 11.0.0.0-169.253.255.255, protocol: all}
      - {destination: 169.255.0.0-172.15.255.255, protocol: all}
      - {destination: 172.32.0.0-192.167.255.255, protocol: all}
      - {destination: 192.169.0.0-255.255.255.255, protocol: all}
    - name: dns
      rules:
      - {destination: 0.0.0.0/0, ports: '53', protocol: tcp}
      - {destination: 0.0.0.0/0, ports: '53', protocol: udp}
    srv_api_uri: https://api.10.158.246.86.xip.io
    staging_upload_password: PASSWORD
    staging_upload_user: staging_upload_user
  ccdb:
    address: 10.158.246.84
    databases:
    - {name: ccdb, tag: cc}
    db_scheme: postgres
    port: 5524
    roles:
    - {name: ccadmin, password: PASSWORD, tag: admin}
  databases:
    databases:
    - {name: ccdb, tag: cc, citext: true}
    - {name: uaadb, tag: uaa, citext: true}
    port: 5524
    roles:
    - {name: ccadmin, password: PASSWORD, tag: admin}
    - {name: uaaadmin, password: PASSWORD, tag: admin}
  dea_next:
    advertise_interval_in_seconds: 5
    heartbeat_interval_in_seconds: 10
    memory_mb: 2048
  description: abc
  domain: 10.158.246.86.xip.io
  etcd:
    machines: [10.158.246.82]
  hm9000:
    url: https://hm9000.10.158.246.86.xip.io
  logger_endpoint:
    port: 4443
  loggregator_endpoint:
    shared_secret: PASSWORD
  login:
    protocol: https
    deployment: cf-deployment
  metron_endpoint:
    shared_secret: PASSWORD
  nats:
    machines: [10.158.246.81,10.158.246.94]
    password: PASSWORD
    port: 4222
  ssl:
    skip_cert_verify: true
  system_domain: 10.158.246.86.xip.io
  system_domain_organization: abc
        authorized-grant-types: client_credentials
      cloud_controller_username_lookup:
        authorities: scim.userids
        authorized-grant-types: client_credentials
        secret: PASSWORD
      gorouter:
        authorized-grant-types: client_credentials,refresh_token
        scope: openid,cloud_controller_service_permissions.read
        secret: PASSWORD
      doppler:
        authorities: uaa.resource
        secret: PASSWORD
      login:
        redirect-uri: https://login.10.158.246.86.xip.io
        scope: openid,oauth.approvals
        secret: PASSWORD
      servicesmgmt:
        autoapprove: true
        scope: openid,cloud_controller.read,cloud_controller.write
        secret: PASSWORD
        -----BEGIN RSA PRIVATE KEY-----
        -----END RSA PRIVATE KEY-----

      verification_key: |
        -----BEGIN PUBLIC KEY-----
        -----END PUBLIC KEY-----

    no_ssl: false
    url: https://uaa.10.158.246.86.xip.io

**Comment by yudai** [comment]
Hi, unfortunately, this repo is outdated.

**Comment by lijianxun** [comment]
I don‘t understand, and I use the latest version of bosh-scaler.
ljx@ubuntu:~/bosh-scaler$ git pull
Already up-to-date.

**Comment by ozzozz** [comment]
Hi @lijianxun , now bosh-scaler is hard to maintain the codes.
If you paste your error logs to this issue, it may be helpful to reply to you, but may not be able to solve.

**Comment by lijianxun** [comment]
Hi @ozzozz , I use httperf to measuring web server performance, and hope that the httperf can trigger the out-conditions.
But the bosh-scale get an error when I use httperf :
ljx@ubuntu:~/bosh-scaler$ bundle exec ./bin/scaler ./config/sample.yml
/home/ljx/bosh-scaler/lib/scaler/runner.rb:39: warning: kqueue is not supported on this platform
/home/ljx/bosh-scaler/lib/scaler/collectors/bosh_nats_collector.rb:58:in `block in connect_to_mbus': NATS faild to connected to mbus://nats:nats@10.158.246.80:4222 (RuntimeError)
        from /var/lib/gems/2.1.0/gems/nats-0.4.28/lib/nats/client.rb:506:in `call'
        from /var/lib/gems/2.1.0/gems/nats-0.4.28/lib/nats/client.rb:506:in `receive_data'
        from /var/lib/gems/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
        from /var/lib/gems/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
        from /home/ljx/bosh-scaler/lib/scaler/runner.rb:40:in `start'
        from /home/ljx/bosh-scaler/lib/scaler/runner.rb:7:in `run'
        from ./bin/scaler:5:in `<main>'
ljx@ubuntu:~/bosh-scaler$

**Comment by ozzozz** [comment]
Hi @lijianxun ,

bosh-scaler seems to connect to NATS server in BOSH.
Is 10.158.246.80 the correct BOSH VM's IP address?
Is port 4222 the correct NATS's port?
Is nats:nats the correct NATS's ID/PW?
Check them all, please.

**Comment by lijianxun** [comment]
Hi, I suspect the httperf affect the performance of NATS.
I found another problem:
E, [2015-11-26T02:52:02.721354 #89883] ERROR -- : Updating deployment manifest of cf-deployment failed: undefined method `push_static_ip' for nil:NilClass

What can I do to solve it, thank u very much!
